export * from './authentificationController.service';
import { AuthentificationControllerService } from './authentificationController.service';
export * from './authentificationController.serviceInterface';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './categories.serviceInterface';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './clients.serviceInterface';
export * from './commandesClients.service';
import { CommandesClientsService } from './commandesClients.service';
export * from './commandesClients.serviceInterface';
export * from './commandesFournisseurs.service';
import { CommandesFournisseursService } from './commandesFournisseurs.service';
export * from './commandesFournisseurs.serviceInterface';
export * from './entreprises.service';
import { EntreprisesService } from './entreprises.service';
export * from './entreprises.serviceInterface';
export * from './fournisseurs.service';
import { FournisseursService } from './fournisseurs.service';
export * from './fournisseurs.serviceInterface';
export * from './mouvementsStock.service';
import { MouvementsStockService } from './mouvementsStock.service';
export * from './mouvementsStock.serviceInterface';
export * from './produits.service';
import { ProduitsService } from './produits.service';
export * from './produits.serviceInterface';
export * from './utilisateurs.service';
import { UtilisateursService } from './utilisateurs.service';
export * from './utilisateurs.serviceInterface';
export * from './ventes.service';
import { VentesService } from './ventes.service';
export * from './ventes.serviceInterface';
export const APIS = [AuthentificationControllerService, CategoriesService, ClientsService, CommandesClientsService, CommandesFournisseursService, EntreprisesService, FournisseursService, MouvementsStockService, ProduitsService, UtilisateursService, VentesService];
