/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthentificationRequest } from '../model/models';
import { AuthentificationResponse } from '../model/models';
import { RegisterRequest } from '../model/models';
import { UserProfileResponse } from '../model/models';
import { Utilisateur } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthentificationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param authentificationRequest 
     */
    authenticate(authentificationRequest: AuthentificationRequest, extraHttpRequestParams?: any): Observable<AuthentificationResponse>;

    /**
     * 
     * 
     */
    getAllUsers(extraHttpRequestParams?: any): Observable<Array<Utilisateur>>;

    /**
     * 
     * 
     */
    getUserProfile(extraHttpRequestParams?: any): Observable<UserProfileResponse>;

    /**
     * 
     * 
     */
    refreshToken(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param registerRequest 
     */
    register(registerRequest: RegisterRequest, extraHttpRequestParams?: any): Observable<AuthentificationResponse>;

}
