/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Categorydto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CategoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Supprimer une catégorie
     * Cette méthode permet de supprimer une catégorie par son ID.
     * @param idCategory 
     */
    delete8(idCategory: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Renvoi de la liste des catégories
     * Cette méthode permet de chercher et renvoyer la liste des catégories présentes dans la BDD.
     */
    findAll8(extraHttpRequestParams?: any): Observable<Array<Categorydto>>;

    /**
     * Rechercher une catégorie par CODE
     * Cette méthode permet de chercher une catégorie par son CODE.
     * @param codeCategory 
     */
    findByCode3(codeCategory: string, extraHttpRequestParams?: any): Observable<Categorydto>;

    /**
     * Rechercher une catégorie par ID
     * Cette méthode permet de chercher une catégorie par son ID.
     * @param idCategory 
     */
    findById8(idCategory: number, extraHttpRequestParams?: any): Observable<Categorydto>;

    /**
     * Enregistrer une catégorie
     * Cette méthode permet d\&#39;enregistrer ou de modifier une catégorie.
     * @param categorydto 
     */
    save8(categorydto: Categorydto, extraHttpRequestParams?: any): Observable<Categorydto>;

}
