/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ClientDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ClientsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Supprimer un client
     * Cette méthode permet de supprimer un client par son ID.
     * @param idClient 
     */
    delete7(idClient: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Renvoi la liste des clients
     * Cette méthode permet de chercher et renvoyer la liste des clients présents dans la BDD.
     */
    findAll7(extraHttpRequestParams?: any): Observable<Array<ClientDto>>;

    /**
     * Rechercher un client par ID
     * Cette méthode permet de chercher un client par son ID.
     * @param idClient 
     */
    findById7(idClient: number, extraHttpRequestParams?: any): Observable<ClientDto>;

    /**
     * Enregistrer un client
     * Cette méthode permet d\&#39;enregistrer ou de modifier un client.
     * @param clientDto 
     */
    save7(clientDto: ClientDto, extraHttpRequestParams?: any): Observable<ClientDto>;

}
