/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { EntrepriseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EntreprisesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Supprimer une entreprise
     * Cette méthode permet de supprimer une entreprise par son ID
     * @param idEntreprise 
     */
    delete4(idEntreprise: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Lister toutes les entreprises
     * Cette méthode permet de renvoyer la liste de toutes les entreprises enregistrées dans la base de données
     */
    findAll4(extraHttpRequestParams?: any): Observable<Array<EntrepriseDto>>;

    /**
     * Rechercher une entreprise par ID
     * Cette méthode permet de rechercher une entreprise grâce à son ID
     * @param idEntreprise 
     */
    findById4(idEntreprise: number, extraHttpRequestParams?: any): Observable<EntrepriseDto>;

    /**
     * Enregistrer une entreprise
     * Cette méthode permet de créer ou de modifier une entreprise
     * @param entrepriseDto 
     */
    save4(entrepriseDto: EntrepriseDto, extraHttpRequestParams?: any): Observable<EntrepriseDto>;

}
