/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { FournisseurDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FournisseursServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Supprimer un fournisseur
     * Cette méthode permet de supprimer un fournisseur par son ID.
     * @param idFournisseur 
     */
    delete3(idFournisseur: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Lister tous les fournisseurs
     * Cette méthode permet de lister tous les fournisseurs enregistrés dans la base de données.
     */
    findAll3(extraHttpRequestParams?: any): Observable<Array<FournisseurDto>>;

    /**
     * Rechercher un fournisseur par ID
     * Cette méthode permet de rechercher un fournisseur grâce à son ID.
     * @param idFournisseur 
     */
    findById3(idFournisseur: number, extraHttpRequestParams?: any): Observable<FournisseurDto>;

    /**
     * Enregistrer un fournisseur
     * Cette méthode permet d\&#39;enregistrer ou de modifier un fournisseur.
     * @param fournisseurDto 
     */
    save3(fournisseurDto: FournisseurDto, extraHttpRequestParams?: any): Observable<FournisseurDto>;

}
