/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MvmStockDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MouvementsStockServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Correction négative de stock
     * Cette méthode permet d\&#39;enregistrer une correction négative sur le stock.
     * @param mvmStockDto 
     */
    correctionStockNeg(mvmStockDto: MvmStockDto, extraHttpRequestParams?: any): Observable<MvmStockDto>;

    /**
     * Correction positive de stock
     * Cette méthode permet d\&#39;enregistrer une correction positive sur le stock.
     * @param mvmStockDto 
     */
    correctionStockPos(mvmStockDto: MvmStockDto, extraHttpRequestParams?: any): Observable<MvmStockDto>;

    /**
     * Entrée de stock
     * Cette méthode permet d\&#39;enregistrer un mouvement d\&#39;entrée de stock.
     * @param mvmStockDto 
     */
    entreeStock(mvmStockDto: MvmStockDto, extraHttpRequestParams?: any): Observable<MvmStockDto>;

    /**
     * Historique des mouvements d\&#39;un article
     * Cette méthode permet de récupérer les mouvements de stock pour un article donné.
     * @param idProduit 
     */
    mvtStkProduit(idProduit: number, extraHttpRequestParams?: any): Observable<Array<MvmStockDto>>;

    /**
     * Sortie de stock
     * Cette méthode permet d\&#39;enregistrer un mouvement de sortie de stock.
     * @param mvmStockDto 
     */
    sortieStock(mvmStockDto: MvmStockDto, extraHttpRequestParams?: any): Observable<MvmStockDto>;

    /**
     * Stock Réel
     * Cette méthode permet de récupérer le stock réel d\&#39;un article donné.
     * @param idProduit 
     */
    stockReelProduit(idProduit: number, extraHttpRequestParams?: any): Observable<number>;

}
