/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { VenteDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface VentesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Supprimer une vente
     * Cette méthode permet de supprimer une vente en fournissant son ID.
     * @param idVente 
     */
    _delete(idVente: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Lister toutes les ventes
     * Cette méthode permet de récupérer toutes les ventes enregistrées.
     */
    findAll(extraHttpRequestParams?: any): Observable<Array<VenteDto>>;

    /**
     * Rechercher une vente par Code
     * Cette méthode permet de rechercher une vente en utilisant son code.
     * @param codeVente 
     */
    findByCode(codeVente: string, extraHttpRequestParams?: any): Observable<VenteDto>;

    /**
     * Rechercher une vente par ID
     * Cette méthode permet de rechercher une vente en utilisant son ID.
     * @param idVente 
     */
    findById(idVente: number, extraHttpRequestParams?: any): Observable<VenteDto>;

    /**
     * Créer ou modifier une vente
     * Cette méthode permet d\&#39;enregistrer ou de modifier une vente.
     * @param venteDto 
     */
    save(venteDto: VenteDto, extraHttpRequestParams?: any): Observable<VenteDto>;

}
