/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdresseDto } from './adresseDto';


export interface ClientDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    photo?: string;
    adresse?: AdresseDto;
    telephone?: string;
    email?: string;
    idEntreprise?: number;
}

