/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UtilisateurDto } from './utilisateurDto';
import { AdresseDto } from './adresseDto';


export interface EntrepriseDto { 
    id?: number;
    nom?: string;
    description?: string;
    adresse?: AdresseDto;
    codeFiscal?: string;
    photo?: string;
    email?: string;
    telephone?: string;
    siteWeb?: string;
    utilisateurs?: Array<UtilisateurDto>;
}

