/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { Utilisateur } from './utilisateur';


export interface Entreprise { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    nom?: string;
    description?: string;
    adresse?: Adresse;
    codeFiscal?: string;
    photo?: string;
    email?: string;
    telephone?: string;
    siteWeb?: string;
    utilisateurs?: Array<Utilisateur>;
}

