/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProduitDto } from './produitDto';
import { VenteDto } from './venteDto';


export interface LigneVenteDto { 
    id?: number;
    vente?: VenteDto;
    produit?: ProduitDto;
    quantite?: number;
    prixUnitaire?: number;
    idEntreprise?: number;
}

