/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Utilisateur } from './utilisateur';


export interface Roles { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    roleNom?: string;
    utilisateur?: Utilisateur;
    permissions?: Array<Roles.PermissionsEnum>;
}
export namespace Roles {
    export type PermissionsEnum = 'PRODUIT_READ' | 'PRODUIT_UPDATE' | 'PRODUIT_CREATE' | 'PRODUIT_DELETE' | 'CLIENT_READ' | 'CLIENT_UPDATE' | 'CLIENT_CREATE' | 'CLIENT_DELETE' | 'COMMANDE_READ' | 'COMMANDE_UPDATE' | 'COMMANDE_CREATE' | 'COMMANDE_DELETE' | 'FOURNISSEUR_READ' | 'FOURNISSEUR_UPDATE' | 'FOURNISSEUR_CREATE' | 'FOURNISSEUR_DELETE' | 'UTILISATEUR_READ' | 'UTILISATEUR_UPDATE' | 'UTILISATEUR_CREATE' | 'UTILISATEUR_DELETE';
    export const PermissionsEnum = {
        ProduitRead: 'PRODUIT_READ' as PermissionsEnum,
        ProduitUpdate: 'PRODUIT_UPDATE' as PermissionsEnum,
        ProduitCreate: 'PRODUIT_CREATE' as PermissionsEnum,
        ProduitDelete: 'PRODUIT_DELETE' as PermissionsEnum,
        ClientRead: 'CLIENT_READ' as PermissionsEnum,
        ClientUpdate: 'CLIENT_UPDATE' as PermissionsEnum,
        ClientCreate: 'CLIENT_CREATE' as PermissionsEnum,
        ClientDelete: 'CLIENT_DELETE' as PermissionsEnum,
        CommandeRead: 'COMMANDE_READ' as PermissionsEnum,
        CommandeUpdate: 'COMMANDE_UPDATE' as PermissionsEnum,
        CommandeCreate: 'COMMANDE_CREATE' as PermissionsEnum,
        CommandeDelete: 'COMMANDE_DELETE' as PermissionsEnum,
        FournisseurRead: 'FOURNISSEUR_READ' as PermissionsEnum,
        FournisseurUpdate: 'FOURNISSEUR_UPDATE' as PermissionsEnum,
        FournisseurCreate: 'FOURNISSEUR_CREATE' as PermissionsEnum,
        FournisseurDelete: 'FOURNISSEUR_DELETE' as PermissionsEnum,
        UtilisateurRead: 'UTILISATEUR_READ' as PermissionsEnum,
        UtilisateurUpdate: 'UTILISATEUR_UPDATE' as PermissionsEnum,
        UtilisateurCreate: 'UTILISATEUR_CREATE' as PermissionsEnum,
        UtilisateurDelete: 'UTILISATEUR_DELETE' as PermissionsEnum
    };
}


