/**
 * Gestion de stock REST API
 * Documentation pour l\'API REST Gestion des stocks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: wiamejaoui.wj@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Adresse } from './adresse';
import { Entreprise } from './entreprise';
import { GrantedAuthority } from './grantedAuthority';
import { Roles } from './roles';


export interface Utilisateur { 
    id?: number;
    creationDate?: string;
    lastModifiedDate?: string;
    nom?: string;
    prenom?: string;
    email?: string;
    dateDeNaissance?: string;
    moteDePasse?: string;
    adresse?: Adresse;
    photo?: string;
    entreprise?: Entreprise;
    roles?: Array<Roles>;
    password?: string;
    enabled?: boolean;
    username?: string;
    authorities?: Array<GrantedAuthority>;
    accountNonLocked?: boolean;
    credentialsNonExpired?: boolean;
    accountNonExpired?: boolean;
}

